@startuml
skinparam packageStyle rectangle
rectangle Aula_Virtual{

actor Profesor

actor Alumno


    node Grupo
    node Curso

    Profesor --> (Administrar Grupo)
    Profesor --> (Administrar Asignatura)
    

    (Crear Asignatura) ..> (Asignatura) : include
    (Administrar Asignatura) ..> (Asignatura) : include
    (Administrar Asignatura) ..> (Alterar Contenido) : extends
  (Alterar Notas) ..> (Administrar Asignatura) : extends
    (Alterar tareas) ..> (Administrar Asignatura) : extends
  
    
    Profesor --> (Alterar Grupos)
    (Grupo) --> (Curso) 
(Creacion Grupo) ..> (Grupo) : extends
    (Alterar Grupos) ..> (Grupo) : include
    (Administrar Grupo) ..> (Grupo) : include
    
    
    Alumno -- (Curso)
    (Alterar Alumno) .. (Administrar Grupo) : extends
(Entregar tareas) ..> (Curso) : extends
    (Eliminar Alumno) ..> (Administrar Grupo) : extends
(Consultar Notas) ..> (Curso) : extends
    (Añadir Alumno) ..> (Administrar Grupo) : extends
    
    (Curso) ..> (Asignatura) : include
    
    (Consultar contenido) ..> (Curso) : extemds
    
}
@enduml
